/**
 * ========================================
 * ADDRESS BOOK - MOCK DATA
 * ========================================
 */

import { Contact } from "./types";

export const mockContacts: Contact[] = [
  {
    id: "contact_1",
    name: "John Doe",
    company: "Tech Solutions Inc.",
    telephone: "+1-555-0101",
    mobilePhone: "+1-555-0102",
    email: "john.doe@techsolutions.com",
    birthday: "1990-05-15",
    jobTitle: "Senior Developer",
    department: "IT",
    category: "Company",
    isPublic: true,
    createdBy: "emp_001",
    companyCode: "DEMO",
    street: "123 Main Street",
    city: "San Francisco",
    stateProvince: "CA",
    postalCode: "94102",
    countryRegion: "USA",
    workplace: "HQ Building A",
    workplacePhone: "+1-555-1000",
    division: "Engineering",
    createdAt: new Date("2025-10-15T10:00:00"),
    updatedAt: new Date("2025-10-15T10:00:00"),
  },
  {
    id: "contact_2",
    name: "Jane Smith",
    company: "Marketing Pro",
    telephone: "+1-555-0201",
    mobilePhone: "+1-555-0202",
    email: "jane.smith@marketingpro.com",
    jobTitle: "Marketing Manager",
    department: "Marketing",
    category: "Public",
    isPublic: true,
    createdBy: "emp_001",
    companyCode: "DEMO",
    street: "456 Oak Avenue",
    city: "Los Angeles",
    stateProvince: "CA",
    postalCode: "90001",
    countryRegion: "USA",
    createdAt: new Date("2025-10-16T14:30:00"),
    updatedAt: new Date("2025-10-16T14:30:00"),
  },
  {
    id: "contact_3",
    name: "Robert Johnson",
    company: "Johnson & Associates",
    telephone: "+1-555-0301",
    mobilePhone: "+1-555-0302",
    email: "robert@johnsonlaw.com",
    jobTitle: "Partner",
    category: "Personal",
    isPublic: false,
    createdBy: "emp_001",
    companyCode: "DEMO",
    city: "New York",
    stateProvince: "NY",
    countryRegion: "USA",
    createdAt: new Date("2025-10-17T09:15:00"),
    updatedAt: new Date("2025-10-17T09:15:00"),
  },
  {
    id: "contact_4",
    name: "Sarah Williams",
    company: "Tech Solutions Inc.",
    telephone: "+1-555-0401",
    mobilePhone: "+1-555-0402",
    email: "sarah.williams@techsolutions.com",
    birthday: "1988-11-22",
    jobTitle: "HR Manager",
    department: "HR",
    category: "Company",
    isPublic: true,
    createdBy: "emp_001",
    companyCode: "DEMO",
    workplace: "HQ Building B",
    workplacePhone: "+1-555-1001",
    division: "Human Resources",
    createdAt: new Date("2025-10-18T11:00:00"),
    updatedAt: new Date("2025-10-18T11:00:00"),
  },
  {
    id: "contact_5",
    name: "Michael Brown",
    telephone: "+1-555-0501",
    mobilePhone: "+1-555-0502",
    email: "mbrown@email.com",
    category: "Personal",
    isPublic: false,
    createdBy: "emp_001",
    companyCode: "DEMO",
    createdAt: new Date("2025-10-19T16:20:00"),
    updatedAt: new Date("2025-10-19T16:20:00"),
  },
  {
    id: "contact_6",
    name: "Emily Davis",
    company: "Design Studio",
    telephone: "+1-555-0601",
    email: "emily@designstudio.com",
    jobTitle: "Creative Director",
    category: "Public",
    isPublic: true,
    createdBy: "emp_001",
    companyCode: "DEMO",
    city: "Austin",
    stateProvince: "TX",
    countryRegion: "USA",
    createdAt: new Date("2025-10-20T13:45:00"),
    updatedAt: new Date("2025-10-20T13:45:00"),
  },
];
